import {sceneIllustration} from './scenes.js';
import {escape} from '../utils/dom.js';
import {references} from '../content/references.js';
export function moduleHTML(m){
const paragraphs=m.analysis.map(p=>`<p>${escape(p)}</p>`).join('');
const sources=m.sources.map(id=>{const r=references.find(r=>r.id===id);return `<a href="#source-${id}">${escape(r.author)}</a>`}).join(' · ');
return `<section id="module-${m.id}" class="module act-${m.act}" data-module="${m.id}" aria-labelledby="module-title-${m.id}">
<div class="module-intro"><div class="module-number"><span>${String(m.id).padStart(2,'0')}</span><small>CHAPTER</small></div><div><span class="eyebrow">ACT ${m.act} · ${escape(m.space)}</span><h2 id="module-title-${m.id}">${escape(m.title)}</h2><p class="essential-question">${escape(m.question)}</p></div></div>
<div class="module-primary"><div class="primary-copy"><p class="module-lead">${escape(m.lead)}</p><div class="definition"><span class="eyebrow">A working definition</span><p>${escape(m.definition)}</p></div><details class="instructor-prompt"><summary>Open a discussion</summary><p>${escape(m.reflection)}</p><p class="discussion-note">Invite a concrete example, a counterexample, and one condition that would change the decision.</p></details></div><figure class="concept-figure">${sceneIllustration(m)}<div class="model-orbit" aria-hidden="true"><span class="orbit-center">${m.act===1?'PURPOSE':m.act===2?'PEOPLE':'PRACTICE'}</span>${m.model.map((label,i)=>`<span class="orbit-item" style="--i:${i};--n:${m.model.length}"><b>${String(i+1).padStart(2,'0')}</b>${escape(label)}</span>`).join('')}</div><figcaption>${escape(m.model.join(' → '))}. These elements must work together; the diagram is a conceptual model, not a causal finding.</figcaption></figure></div>
<details class="deep-learning"><summary><span>Go deeper</span><span>Analysis, classroom examples & leadership practice <b aria-hidden="true">+</b></span></summary><div class="deep-body"><div class="analysis">${paragraphs}</div><div class="case-grid"><article><span class="eyebrow">Elementary application</span><h3>From a classroom decision…</h3><p>${escape(m.elementary)}</p></article><article><span class="eyebrow">Secondary application</span><h3>…to a schoolwide responsibility.</h3><p>${escape(m.secondary)}</p></article></div><div class="considerations"><article><h3>Access, language & learner variability</h3><p>${escape(m.inclusion)}</p></article><article><h3>Limits & ethical considerations</h3><p>${escape(m.limits)}</p></article></div><h3>Leadership moves</h3><ol class="strategy-list">${m.strategies.map(s=>`<li>${escape(s)}</li>`).join('')}</ol><p class="reading-links">Reading connections: ${sources}. Source access notes are in the references.</p></div></details>
<div class="application-heading"><span class="eyebrow">Put your judgment to work</span><span>INTERACTIVE APPLICATION <span aria-hidden="true">↘</span></span></div><div class="activity" id="activity-${m.id}" data-activity="${m.activity}"></div>
<div class="module-reflection"><div><span class="eyebrow">Pause & connect</span><h3>${escape(m.reflection)}</h3><label class="sr-only" for="reflection-${m.id}">Reflection for chapter ${m.id}</label><textarea id="reflection-${m.id}" data-reflection="${m.id}" rows="3" placeholder="A thought, a question, or your next action. Avoid personal or student information."></textarea><span class="storage-status">Optional reflections stay in this browser on this device.</span></div><aside><span class="eyebrow">Carry this forward</span><p>${escape(m.synthesis)}</p><button class="complete-button" data-complete="${m.id}" aria-pressed="false"><span aria-hidden="true">○</span> Mark chapter complete</button></aside></div>
</section>`;
}
