import {modules} from './content/modules.js';
import {framework,objectives,references} from './content/references.js';
import {moduleHTML} from './components/module.js';
import {environment} from './components/environment.js';
import {initActivities} from './interactions/activities.js';
import {state,save,reset,storageAvailable} from './utils/storage.js';
import {escape,announce} from './utils/dom.js';
import {initStory} from './animations/story.js';
const $=s=>document.querySelector(s);
const fullscreenIcon='<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>';$('#fullscreen').innerHTML=fullscreenIcon;
$('#opening-environment').innerHTML=environment('opening');$('#closing-environment').innerHTML=environment('closing');
const frameworkHTML=()=>framework.map(f=>`<div class="framework-domain"><strong>${f.letter}</strong><span>${f.title}</span></div>`).join('');
$('#framework-overview').innerHTML=frameworkHTML();$('#framework-closing').innerHTML=frameworkHTML();
const actNames=['Establish the direction','Build the conditions','Lead with evidence'];
$('#journey-map').innerHTML=[1,2,3].map(act=>`<div class="act-heading"><span>0${act}</span><h3>${actNames[act-1]}</h3><small>${act===1?'PURPOSE & CULTURE':act===2?'CAPACITY & RESPONSIBILITY':'INNOVATION & COMMITMENT'}</small></div><div class="chapter-cards">${modules.filter(m=>m.act===act).map(m=>`<a class="chapter-card" href="#module-${m.id}"><span>${String(m.id).padStart(2,'0')}</span><div>${m.short}<small>${m.space}</small></div></a>`).join('')}</div>`).join('');
$('#objectives-list').innerHTML=objectives.map(o=>`<li>${o}</li>`).join('');$('#modules').innerHTML=modules.map(moduleHTML).join('');
$('#chapter-list').innerHTML=modules.map(m=>`<li><a href="#module-${m.id}" data-chapter="${m.id}"><span>${String(m.id).padStart(2,'0')}</span><span>${m.title}</span><span class="chapter-check" aria-label="Not completed"></span></a></li>`).join('');
$('#reference-list').innerHTML=references.map(r=>`<li id="source-${r.id}"><div><h3>${escape(r.title)}</h3><p class="source-author">${escape(r.author)} · ${escape(r.year)}</p><p class="source-note">${escape(r.note)}</p><span class="source-status">${escape(r.status)}</span>${r.url?`<br><a href="${r.url}" target="_blank" rel="noopener noreferrer">Open source ↗ <span class="sr-only">${escape(r.title)}, opens a new tab</span></a>`:''}</div></li>`).join('');
initActivities(modules);let current=0;
function updateChapter(id){current=id;const m=modules.find(m=>m.id===id);$('#current-module').textContent=m?`${String(id).padStart(2,'0')} / 15 · ${m.short}`:id===16?'Your leadership commitment':id===17?'Sources & reading notes':'Overview';$('#previous-module').href=id<=1?'#overview':id===17?'#closing':`#module-${Math.min(15,id-1)}`;$('#next-module').href=id===0?'#module-1':id<15?`#module-${id+1}`:id===15?'#closing':'#references';document.querySelectorAll('[data-chapter]').forEach(a=>{if(+a.dataset.chapter===id)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});}
const queueStory=initStory(updateChapter);
function updateCompletion(){document.querySelectorAll('[data-complete]').forEach(b=>{const done=state.completed.includes(+b.dataset.complete);b.setAttribute('aria-pressed',done);b.innerHTML=done?'<span aria-hidden="true">✓</span> Chapter complete':'<span aria-hidden="true">○</span> Mark chapter complete';});document.querySelectorAll('[data-chapter]').forEach(a=>{const done=state.completed.includes(+a.dataset.chapter);a.querySelector('.chapter-check').textContent=done?'✓':'';a.querySelector('.chapter-check').setAttribute('aria-label',done?'Completed':'Not completed');});$('#completion-count').textContent=`${state.completed.length} / 15 complete`;}
updateCompletion();document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const n=+b.dataset.complete;state.completed=state.completed.includes(n)?state.completed.filter(x=>x!==n):[...state.completed,n];save();updateCompletion();announce(`Chapter ${n} ${state.completed.includes(n)?'marked complete':'marked incomplete'}.`);});
document.querySelectorAll('[data-reflection]').forEach(t=>{t.value=typeof state.reflections[t.dataset.reflection]==='string'?state.reflections[t.dataset.reflection]:'';t.oninput=()=>{state.reflections[t.dataset.reflection]=t.value;const stored=save();t.nextElementSibling.textContent=stored?'Saved in this browser on this device.':'Storage unavailable. Copy this reflection to keep it.';};});
function applyMode(mode,preserve=true){const anchor=preserve?document.querySelector(current>0&&current<=15?`#module-${current}`:'#overview'):null;const before=anchor?.getBoundingClientRect().top;state.mode=mode;save();document.body.classList.toggle('study-mode',mode==='study');$('#presenter-mode').setAttribute('aria-pressed',mode==='presenter');$('#study-mode').setAttribute('aria-pressed',mode==='study');document.querySelectorAll('.deep-learning').forEach(d=>d.open=mode==='study');if(anchor&&before!==undefined){const delta=anchor.getBoundingClientRect().top-before;if(Math.abs(delta)>1)window.scrollBy({top:delta,behavior:'instant'});}queueStory();}
$('#presenter-mode').onclick=()=>applyMode('presenter');$('#study-mode').onclick=()=>applyMode('study');applyMode(state.mode,false);
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');function applyMotion(){const reduced=state.motion||motionQuery.matches;document.body.classList.toggle('reduced-motion',reduced);$('#motion-toggle').setAttribute('aria-pressed',reduced);$('#motion-toggle').setAttribute('aria-label',reduced?'Animation reduced; enable if system preference permits':'Reduce animation');$('#motion-toggle').innerHTML=reduced?'<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><path d="M7 4l12 8-12 8z" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>':'<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><path d="M8 4v16M16 4v16" stroke="currentColor" stroke-width="2"/></svg>';}$('#motion-toggle').onclick=()=>{state.motion=!state.motion;save();applyMotion();announce(document.body.classList.contains('reduced-motion')?'Animation reduced.':'Animation enabled.');};motionQuery.addEventListener?.('change',applyMotion);applyMotion();
const panel=$('#chapters');function closeChapters(returnFocus=false){panel.hidden=true;$('#chapters-toggle').setAttribute('aria-expanded','false');if(returnFocus)$('#chapters-toggle').focus();}$('#chapters-toggle').onclick=()=>{const open=panel.hidden;panel.hidden=!open;$('#chapters-toggle').setAttribute('aria-expanded',open);if(open)panel.querySelector('a').focus();};$('#chapters-close').onclick=()=>closeChapters(true);
panel.querySelectorAll('a').forEach(a=>a.onclick=()=>{closeChapters();const target=document.querySelector(a.hash);if(target?.dataset.module)updateChapter(+target.dataset.module);if(target){target.tabIndex=-1;target.focus({preventScroll:true});}});
document.addEventListener('click',e=>{if(!panel.hidden&&!panel.contains(e.target)&&!$('#chapters-toggle').contains(e.target))closeChapters();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){closeChapters(true);return;}if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.target.closest('input,textarea,select,button,summary,[contenteditable]')||!panel.hidden)return;if(e.key==='PageDown'||e.key==='PageUp'){e.preventDefault();const focusedModule=e.target.closest('.module');const n=focusedModule?+focusedModule.dataset.module:current;const href=e.key==='PageDown'?(n<15?'#module-'+(n+1):n===15?'#closing':'#references'):(n<=1?'#overview':n===17?'#closing':'#module-'+Math.min(15,n-1));location.hash=href;const target=document.querySelector(href);if(target){target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView();}}});
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else announce('Fullscreen is unavailable in this browser.');}catch{announce('Fullscreen is unavailable in this browser or embedded context.');}};document.addEventListener('fullscreenchange',()=>$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen'));
$('#reset-progress').onclick=()=>{$('#reset-confirm').hidden=false;$('#confirm-reset').focus();};$('#cancel-reset').onclick=()=>{$('#reset-confirm').hidden=true;$('#reset-progress').focus();};$('#confirm-reset').onclick=()=>{reset();location.reload();};
if(!storageAvailable)document.querySelectorAll('.storage-status').forEach(e=>e.textContent='Storage unavailable. Work stays in this session; export anything you want to keep.');
if(location.hash)requestAnimationFrame(()=>{document.getElementById(location.hash.slice(1))?.scrollIntoView({behavior:'instant'});queueStory();});
