import assert from 'node:assert/strict';import {mkdir,writeFile,readFile} from 'node:fs/promises';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);let playwright;try{playwright=require('playwright');}catch{if(process.env.PLAYWRIGHT_MODULE)playwright=require(process.env.PLAYWRIGHT_MODULE);else throw new Error('Install Playwright in a separate tools directory or provide PLAYWRIGHT_MODULE; see README.');}
const {chromium}=playwright;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});const base=process.env.TEST_URL||'http://127.0.0.1:8001/dist/';await mkdir('test-results',{recursive:true});let checks=0;const ok=(condition,message)=>{assert.ok(condition,message);checks++;};
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#activity-15 form');
 ok(await page.locator('.module').count()===15,'15 rendered modules');ok(await page.locator('.deep-learning[open]').count()===0,'Presenter default');await page.screenshot({path:'test-results/desktop.png',fullPage:false});
 await page.locator('#activity-1 [data-school="A"] [data-facet="Teacher practice"]').click();ok((await page.locator('#activity-1 [data-school="A"] .feedback').textContent()).includes('checking workload'),'School A consequences');await page.locator('#activity-1 [data-school="B"] [data-facet="Accountability"]').click();ok((await page.locator('#activity-1 [data-school="B"] .feedback').textContent()).includes('Named owners'),'School B consequences');
 await page.locator('#vision-equity').fill('Screen-reader access verified with specialists');await page.locator('#vision-evidence').fill('Students explain changes to their reasoning');await page.locator('#vision-evaluate').click();ok((await page.locator('#activity-2 .feedback').textContent()).includes('baseline'),'Vision feedback');
 for(const id of [3,8]){for(let i=0;i<3;i++){await page.locator(`#activity-${id} [data-case="${i}"]`).click();for(let a=0;a<3;a++){await page.locator(`#activity-${id} [data-answer="${a}"]`).click();ok((await page.locator(`#activity-${id} .feedback`).textContent()).length>50,'Dialogue feedback');}}}
 for(const name of ['listen','errors','time','owners'])await page.locator(`input[name="culture"][value="${name}"]`).check();ok(await page.locator('#activity-4 svg').getAttribute('class')==='network-svg active','Culture network');
 for(const name of ['literacy','privacy','model','coach','review'])await page.locator(`input[name="learning"][value="${name}"]`).check();await page.locator('#learning-review').click();ok((await page.locator('#learning-hours').textContent()).includes('6 / 6'),'Learning budget');ok((await page.locator('#activity-5 .feedback').textContent()).includes('transfer'),'Learning review');await page.locator('input[value="features"]').check();await page.locator('#learning-review').click();ok((await page.locator('#activity-5 .feedback').textContent()).includes('exceeds'),'Learning constraints');
 for(const d of await page.locator('#activity-6 details summary').all())await d.click();await page.locator('#governance-rationale').fill('Require privacy terms, verified accessibility, incident ownership and a review date.');for(const choice of ['approve','hold','decline']){await page.locator(`[data-verdict="${choice}"]`).click();ok((await page.locator('#activity-6 .feedback').textContent()).length>100,'Vendor review');}
 for(const value of ['formats','language','choice','offline'])await page.locator(`input[name="inclusive"][value="${value}"]`).check();await page.locator('#inclusive-review').click();ok((await page.locator('#activity-7 .feedback').textContent()).includes('opens access'),'Inclusive redesign');await page.locator('input[name="inclusive"][value="auto"]').check();await page.locator('#inclusive-review').click();ok((await page.locator('#activity-7 .feedback').textContent()).includes('inappropriate'),'Inclusive risky choice');
 for(const value of ['checkpoint','performance','reflection','rules','rubric','detector'])await page.locator(`input[name="assessment"][value="${value}"]`).check();await page.locator('#assessment-review').click();ok((await page.locator('#activity-9 .feedback').textContent()).includes('sole reliance'),'Assessment evidence');
 for(const value of ['ai','peer','grading']){await page.locator(`[data-proposal="${value}"]`).click();ok((await page.locator('#activity-10 .feedback').textContent()).length>100,'Innovation choice');}
 for(const value of ['scale','cause','study']){await page.locator(`[data-interpretation="${value}"]`).click();ok((await page.locator('#activity-11 .feedback').textContent()).length>100,'Data interpretation');}
 for(const value of ['feedback','translation','scale']){await page.locator('#policy-dilemma').selectOption(value);ok((await page.locator('#policy-ed').textContent()).length>50,'Policy lens');}
 for(let i=0;i<4;i++){await page.locator(`[data-lens="${i}"]`).click();ok((await page.locator('#activity-13 .feedback').textContent()).length>100,'Future capability');}
 for(let stage=0;stage<5;stage++){await page.locator('[data-decision="1"]').click();await page.locator('#simulation-next').click();}ok(await page.locator('.simulation-profile').count()===1,'Simulation profile');ok((await page.locator('.simulation-profile').textContent()).includes('not a validated'),'Profile qualification');await page.locator('#simulation-replay').click();ok(await page.locator('[data-decision]').count()===3,'Simulation replay');
 for(let stage=0;stage<5;stage++){await page.locator('[data-decision="0"]').click();await page.locator('#simulation-next').click();}ok((await page.locator('.simulation-profile').textContent()).includes('important tensions'),'Alternate branching profile');await page.locator('#simulation-replay').click();for(let stage=0;stage<5;stage++){await page.locator('[data-decision="2"]').click();await page.locator('#simulation-next').click();}ok(await page.locator('.simulation-profile').count()===1,'Third branch profile');
 await page.locator('#reflection-9').fill('I will distinguish product quality from student reasoning.');await page.locator('[data-complete="9"]').click();await page.locator('#study-mode').click();ok(await page.locator('.deep-learning[open]').count()===15,'Study details open');ok((await page.locator('#current-module').textContent()).includes('09'),'Mode preserves chapter');ok(await page.locator('#reflection-9').inputValue()==='I will distinguish product quality from student reasoning.','Mode preserves reflection');
 await page.locator('#presenter-mode').click();ok(await page.locator('.deep-learning[open]').count()===0,'Presenter details accessible');
 const manifestoValues=['A learning goal comes first.','I verify outputs with trusted evidence.','I protect privacy and retain human judgment.','I check access with learners and specialists.','I learn with colleagues and revise practice.','Pilot one feedback routine, partner with a coach, review reasoning in six weeks.'];let idx=0;for(const area of await page.locator('#manifesto-form textarea').all())await area.fill(manifestoValues[idx++]);await page.locator('#manifesto-form button').click();ok(await page.locator('#manifesto-result').isVisible(),'Manifesto generated');const dlPromise=page.waitForEvent('download');await page.locator('#manifesto-download').click();const dl=await dlPromise;await dl.saveAs('test-results/manifesto.txt');ok((await readFile('test-results/manifesto.txt','utf8')).includes(manifestoValues[5]),'Export includes commitments');
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.locator('#manifesto-copy').click();ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('MY EDUCATIONAL'),'Copy export');await page.evaluate(()=>{window.print=()=>{window.__printed=document.querySelector('#print-manifesto')?.textContent;window.dispatchEvent(new Event('afterprint'));}});await page.locator('#manifesto-print').click();ok((await page.evaluate(()=>window.__printed)).includes('My leadership manifesto'),'Print document created');ok(await page.locator('#print-manifesto').count()===0,'Print cleanup');
 await page.reload({waitUntil:'networkidle'});ok(await page.locator('#reflection-9').inputValue()=== 'I will distinguish product quality from student reasoning.','Reflection restored');ok(await page.locator('[data-complete="9"]').getAttribute('aria-pressed')==='true','Completion restored');ok(await page.locator('#manifesto-result').isVisible(),'Manifesto restored');ok(await page.locator('.simulation-profile').count()===1,'Simulation restored');
 await page.locator('#chapters-toggle').click();await page.keyboard.press('Escape');ok(await page.locator('#chapters').isHidden(),'Escape closes chapters');ok(await page.locator('#chapters-toggle').evaluate(e=>e===document.activeElement),'Focus restored');await page.locator('#chapters-toggle').click();await page.locator('#chapter-list a[href="#module-6"]').click();await page.waitForTimeout(650);ok(page.url().endsWith('#module-6'),'Direct chapter navigation');await page.keyboard.press('PageDown');await page.waitForTimeout(650);ok(page.url().endsWith('#module-7'),'Keyboard next chapter');
 const ids=await page.locator('[id]').evaluateAll(es=>es.map(e=>e.id));ok(new Set(ids).size===ids.length,'Unique DOM IDs');const missingHashes=await page.locator('a[href^="#"]').evaluateAll(es=>es.filter(e=>e.hash&&!document.getElementById(e.hash.slice(1))).map(e=>e.hash));ok(missingHashes.length===0,'All internal anchors resolve');
 ok(requests.every(url=>url.startsWith(new URL(base).origin)),'No external requests or response transmission');ok(errors.length===0,'No JavaScript errors: '+errors.join(';'));
 await page.locator('#chapters-toggle').click();await page.locator('#reset-progress').click();await page.locator('#cancel-reset').click();ok(await page.locator('[data-complete="9"]').getAttribute('aria-pressed')==='true','Cancelled reset preserves progress');await page.locator('#reset-progress').click();await page.locator('#confirm-reset').click();await page.waitForSelector('#manifesto-form');ok(await page.locator('#reflection-9').inputValue()==='','Reset clears reflection');ok((await page.locator('#completion-count').textContent()).includes('0 / 15'),'Reset clears completion');await context.close();
 for(const [name,options] of [['mobile',{viewport:{width:390,height:844},isMobile:true,hasTouch:true}],['tablet',{viewport:{width:768,height:1024}}],['reduced-motion',{viewport:{width:1366,height:768},reducedMotion:'reduce'}]]){
 const c=await browser.newContext(options);const p=await c.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));await p.goto(base+'#module-7',{waitUntil:'networkidle'});ok(await p.locator('.module').count()===15,name+' modules');await p.waitForTimeout(300);ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' no horizontal overflow');await p.locator('#study-mode').click();ok(await p.locator('.deep-learning[open]').count()===15,name+' study');await p.locator('#inclusive-review').click();ok(await p.locator('#activity-7 .feedback').isVisible(),name+' activity');if(name==='reduced-motion')ok(await p.locator('body').evaluate(e=>e.classList.contains('reduced-motion')),'System reduced motion');await p.goto(base);await p.screenshot({path:`test-results/${name}.png`});ok(errs.length===0,name+' no errors');await c.close();}
 const offline=await browser.newContext();await offline.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError')}}));const offpage=await offline.newPage();const offerrors=[];offpage.on('pageerror',e=>offerrors.push(e.message));await offpage.goto(base);await offpage.locator('#reflection-1').fill('Session-only reflection');ok((await offpage.locator('#module-1 .storage-status').textContent()).includes('unavailable'),'Unavailable storage fallback');ok(offerrors.length===0,'Storage fallback no errors');await offline.close();
 console.log(`PASS: ${checks} browser assertions; all 15 activities exercised; production subdirectory, desktop/mobile/tablet/reduced-motion, local state and exports.`);await writeFile('test-results/summary.json',JSON.stringify({checks,errors,date:new Date().toISOString(),testedURL:base},null,2));
}finally{await browser.close();}
