export const schoolCases = {
 A:{title:'School A · Launch first',summary:'The same tool is distributed immediately. Training, review responsibilities, and evaluation are not yet defined.',facets:{'Teacher practice':'Teachers receive accounts but no protected review time. Some trust fluent drafts; others avoid the tool. Likely consequence: inconsistent practice and hidden checking workload. This is a fictional possibility, not a measured outcome.','Learner experience':'A worksheet is accessible for one learner but difficult for another. No alternative route is planned. Likely consequence: access depends on teacher improvisation rather than shared design.','Accountability':'No one owns vendor review or incident response. A concern about data reaches several staff members without a clear next action. A launch date does not substitute for governance.'}},
 B:{title:'School B · Learn before scaling',summary:'A needs assessment and stakeholder consultation inform a bounded pilot. The school reviews privacy and accessibility and schedules professional learning.',facets:{'Teacher practice':'Teachers test synthetic examples, share errors, and record review time. This creates evidence for refining practice. It still requires staffing and does not guarantee time savings.','Learner experience':'Specialists check barriers and an equivalent non-AI route is available. The school samples student understanding rather than assuming a polished output demonstrates learning.','Accountability':'Named owners review vendor practices, hear concerns, and schedule a pilot decision. Leaders can revise or stop the initiative if safeguards or educational benefits remain inadequate.'}}
};
export const facultyCases = [
 {voice:'“I already have too much to do. Is this one more expectation?”',role:'Classroom teacher',options:[['Require weekly AI use','A quota creates compliance without resolving workload. You would need evidence that the use supports the learning goal and time for checking outputs.'],['Ask about workload and protect pilot time','Listening becomes useful when it changes conditions. Remove a competing demand, record drafting plus review time, and revisit whether the practice is worth sustaining.'],['Promise that AI will save time','The promise outruns the evidence. Drafting may be faster while checking and adaptation add work. Test total workload rather than guarantee savings.']]},
 {voice:'“What if the feedback is wrong and a student believes it?”',role:'Secondary teacher',options:[['Tell students the tool is usually accurate','General reassurance does not answer a specific risk. Students need a way to question feedback and teachers need a review responsibility.'],['Co-design a teacher-review and appeal routine','This addresses instructional risk and respects expertise. Start with a narrow task, check the feedback, and let students request a human explanation.'],['Ban every use immediately','Non-use can be appropriate, but this response skips diagnosis. Identify the task and risk first; compare safe alternatives rather than assume one decision fits all contexts.']]},
 {voice:'“Our screen-reader test exposed a barrier.”',role:'Special educator',options:[['Treat access as a launch condition','The barrier is implementation evidence. Pause the affected workflow, involve learners and specialists, and verify a usable alternative before proceeding.'],['Launch and fix it later','Later remediation leaves learners excluded now. A timeline should not override access to the core learning experience.'],['Let individual teachers work around it','An individual workaround can help temporarily, but it shifts a systemic responsibility onto teachers. Give it an owner, resources, and a review date.']]}
];
export const communityCases = [
 {role:'Family member',voice:'“Will my child’s work be used to train a commercial system?”',options:[['The vendor says it is safe.','A general claim does not establish data practices. Explain what is known, what is unverified, and who is reviewing retention, reuse, and disclosure terms.'],['We will verify data use before student-facing use and publish the decision.','This makes a bounded, checkable commitment. Name the review owner and timeline, explain allowable data, and keep a route for follow-up questions.'],['Participation means you agree to everything.','Consent is not a blanket waiver of protections. School obligations, age, institutional rules, and operator practices need review.']]},
 {role:'Student',voice:'“Can I use AI for the assignment, or will I be accused of cheating?”',options:[['It depends; use your judgment.','Students need explicit boundaries. Ambiguity creates unfairness, especially when teachers apply different expectations.'],['Use anything unless a detector flags it.','Detection alone cannot establish misconduct or learning. Define permitted support, required disclosure, and a fair human review process.'],['We will specify allowed assistance, what you must explain, and how to disclose it.','Clear expectations connect integrity to learning. Offer accessible ways to demonstrate reasoning and an appeal route if concerns arise.']]},
 {role:'Multilingual family representative',voice:'“Some families could not read the announcement or attend the meeting.”',options:[['We will add accessible, reviewed language versions and a non-digital feedback route.','Engagement requires usable channels. Ask whether the revised routes work, and show how input affects the decision.'],['They can translate it with the same AI tool.','This makes participation depend on a tool that may be inaccessible or inaccurate. Important communication needs reviewed language access.'],['Attendance was optional.','Optional attendance does not remove the need to seek missing perspectives. Consider flexible times and alternative ways to contribute.']]}
];
export const learningOptions = [
 {id:'literacy',title:'AI foundations & output verification',cost:1,detail:'Compare a generated passage with trusted material; identify hallucinations and limits.',feedback:'Provides a shared foundation. Connect the exercise to the subjects teachers actually teach.'},
 {id:'privacy',title:'Privacy, ethics & appropriate non-use',cost:1,detail:'Practice with synthetic data; rehearse boundaries and an incident response.',feedback:'Protects learners before use. Include accessibility and role-specific responsibilities.'},
 {id:'model',title:'Differentiated peer modeling',cost:1,detail:'Novice and advanced pathways show instructional design and accessible assessment.',feedback:'Honors uneven readiness. Modeling needs a later chance to apply and receive feedback.'},
 {id:'coach',title:'Coached classroom practice',cost:2,detail:'Plan, observe, revise, and examine student evidence with a partner.',feedback:'Connects learning to practice, but consumes protected time and coaching capacity.'},
 {id:'review',title:'PLC evidence & transfer review',cost:1,detail:'Compare work samples, review time, and learner access after a bounded pilot.',feedback:'Checks transfer. Do not substitute attendance or satisfaction for instructional evidence.'},
 {id:'features',title:'Vendor feature demonstration',cost:1,detail:'A tour of current buttons and features.',feedback:'Useful orientation, but insufficient on its own: it does not establish judgment, privacy, or transfer.'}
];
export const simulationStages = [
 {title:'1 · Define the scope',prompt:'The district has a fictional $12,000 pilot budget. Leaders want a visible launch this term. Teachers report uneven readiness. What do you propose?',options:[
 {label:'Spend $9,000 on broad licenses and launch immediately',delta:[-8,-8,-10,-8,-15],cost:9000,feedback:'Visible adoption comes quickly, but only $3,000 remains for review, access, and learning. Undefined instructional aims and uneven readiness create risks. Next, families ask what the launch means for student data.'},
 {label:'Reserve $4,000 for a narrow feedback pilot and protect review time',delta:[8,12,6,8,8],cost:4000,feedback:'A defined task and reserved capacity make the pilot more defensible. It still needs vendor review and an explanation of why a smaller launch is useful. Families want those details.'},
 {label:'Invest $2,000 in a needs assessment and non-AI comparison first',delta:[5,10,8,6,12],cost:2000,feedback:'This preserves resources and clarifies whether AI is needed. Explain the decision timetable so consultation does not become indefinite delay. Families now ask about the proposed next step.'}]},
 {title:'2 · Respond to privacy and access',prompt:'The vendor has not clarified retention or commercial reuse. A keyboard-access test fails. Families are asking whether students must participate.',options:[
 {label:'Accept the marketing assurances and defer the access repair',delta:[-12,-4,-18,-3,-20],feedback:'Unverified claims leave specific risks unresolved. Launching despite an access barrier excludes learners and undermines trust. The issue will need remediation and a revised decision.'},
 {label:'Require documented terms, specialist testing, and an equivalent alternative before student use',delta:[12,5,15,5,18],cost:2000,feedback:'You convert concerns into approval conditions and fund review. A tool may still fail those conditions; a viable alternative prevents pressure to approve it anyway.'},
 {label:'Use only synthetic teacher-planning examples while review continues',delta:[5,7,8,9,12],cost:1000,feedback:'A bounded teacher-only trial allows learning without entering student records. It does not settle vendor or accessibility questions for future student use.'}]},
 {title:'3 · Build educator capacity',prompt:'A novice teacher asks for foundations; an experienced teacher wants autonomy. The literacy coach has limited time. Choose a professional learning plan.',options:[
 {label:'Use a feature webinar and make weekly usage mandatory',delta:[-9,-6,-4,2,-6],cost:500,feedback:'A webinar is inexpensive but a usage quota bypasses the concerns. There is little evidence that teachers can verify outputs or adapt them responsibly.'},
 {label:'Offer foundations, role-based modeling, coaching, and a work-sample review',delta:[10,13,10,16,10],cost:3000,feedback:'The sequence links skill to supported practice and transfer. If the budget is insufficient, narrow the pilot rather than promise coaching without capacity.'},
 {label:'Ask experienced teachers to lead a voluntary inquiry group',delta:[6,7,4,9,4],cost:1000,feedback:'Peer inquiry uses local expertise and respects autonomy. Provide a route for novices and shared safety requirements so participation does not widen readiness differences.'}]},
 {title:'4 · Clarify assessment and integrity',prompt:'An AI-written essay looks excellent. Teachers disagree about whether that proves learning. Students ask what help is permitted.',options:[
 {label:'Let a detector determine misconduct and grade the final essay alone',delta:[-16,-15,-10,-4,-14],feedback:'A detection result alone cannot settle misconduct, and polish does not establish understanding. The approach creates unfairness and weakens the validity of assessment.'},
 {label:'Publish assistance rules and add accessible reasoning checkpoints with human review',delta:[10,18,10,8,12],feedback:'You distinguish product quality from learning evidence and clarify expectations. Keep checkpoints proportionate and allow accommodations without lowering the target construct.'},
 {label:'Require a live oral defense for every learner with no exceptions',delta:[-3,8,-14,-3,0],feedback:'Explanation can reveal reasoning, but a single unaccommodated modality creates barriers. Use accessible alternatives and focus the evidence on disciplinary understanding.'}]},
 {title:'5 · Make the evidence decision',prompt:'After the pilot, usage is high, independent reasoning is nearly unchanged, review time has risen, and some learners report access barriers. Leaders ask you to expand.',options:[
 {label:'Scale now because adoption proves success',delta:[-8,-17,-12,-6,-14],feedback:'Use does not establish improvement. Expansion would amplify unresolved barriers and workload without credible evidence of stronger learning.'},
 {label:'Run another bounded PDSA cycle with access repair and clearer evidence',delta:[8,14,14,9,12],cost:1000,feedback:'You respond to evidence and define a next test. Compare baseline and work samples, document implementation quality, and avoid claiming that a before/after gain proves causation.'},
 {label:'Discontinue the tool and fund a viable non-AI feedback routine',delta:[4,10,8,4,14],feedback:'Stopping can be responsible when the benefits do not justify the cost or barriers. Preserve what the team learned and evaluate the alternative rather than assume it will succeed.'}]}
];
export const indicatorNames = ['Stakeholder trust','Instructional alignment','Equity','Organizational readiness','Risk management'];
